name: PR Validator

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.0
      - uses: hecrj/setup-rust-action@v2.0.1
      - name: Format check
        run: cargo fmt  -- --check
      - name: Build and Lint
        run: cargo clippy --tests -- -D warnings
      - name: Run tests
        run: cargo test --verbose
